/**
 * Step 1: Deploy the OZ deployer account on-chain.
 * Step 2: Declare + deploy CommitmentRegistry using that account.
 *
 * Usage: /opt/homebrew/bin/node setup.mjs
 */

import { RpcProvider, Account, json, hash, CallData, ec, stark } from 'starknet';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const RPC_URL = 'https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/YzVrT5_nZgZhSIQqhq984';

// OZ deployer account (generated by sncast, funded via faucet)
const OZ_ADDRESS    = '0x06d26c20a21470f2caa4809b056fc6f38547c1e8524746b0f8f9d7f0e171ab62';
const OZ_PRIVKEY    = '0x549762d2ba37e43f54e19db117d54fbf0a16882e721a8d8eddf6d16c26ef91f';
const OZ_PUBKEY     = '0x1598b2ebee418d543d5ccce669114911085e67065f85de67d219c07c77b43ae';
const OZ_CLASS_HASH = '0x00e2eb8f5672af4e6a4e8a8f1b44989685e668489b0a25437733756c5a34a1d6';
const OZ_SALT       = '0xb3d0fed8e3731494';

const CONTRACT_DIR = resolve(__dirname, 'target/dev');
const SIERRA_FILE  = resolve(CONTRACT_DIR, 'darkindex_contracts_CommitmentRegistry.contract_class.json');
const CASM_FILE    = resolve(CONTRACT_DIR, 'darkindex_contracts_CommitmentRegistry.compiled_contract_class.json');
const RELAY_ENV    = resolve(__dirname, '../relay/.env');

// Network CASM hash for our Sierra (obtained from sncast declare error output)
const NETWORK_CASM_HASH = '0x16daeb8fa91db808610437c84678420cbeadaf8ee60df089ffef14220e4b87d';

const CHAIN_ID = '0x534e5f5345504f4c4941'; // SN_SEPOLIA

const RESOURCE_BOUNDS = {
  l1_gas:      { max_amount: '0x186a0', max_price_per_unit: '0x80a2ef23e03a' },
  l2_gas:      { max_amount: '0xd6d80', max_price_per_unit: '0x80a2ef23e03a' },
  l1_data_gas: { max_amount: '0x186a0', max_price_per_unit: '0x80a2ef23e03a' },
};

async function callRpcRaw(method, params) {
  const res = await fetch(RPC_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
  });
  return res.json();
}

function toHex(n) {
  return '0x' + BigInt(n).toString(16);
}

function signHash(txHash, privkey) {
  const sig = ec.starkCurve.sign(txHash, privkey);
  return [toHex(sig.r), toHex(sig.s)];
}

async function main() {
  const provider = new RpcProvider({ nodeUrl: RPC_URL });
  const block = await provider.getBlockLatestAccepted();
  console.log('Latest block:', block.block_number);

  // ── Step 1: Deploy OZ account if not yet deployed ──────────────────────────
  let ozDeployed = false;
  try {
    const nonce = await provider.getNonceForAddress(OZ_ADDRESS);
    ozDeployed = BigInt(nonce) >= 0n;
    console.log('\nOZ account already deployed. Nonce:', nonce);
  } catch {
    console.log('\nOZ account not yet deployed.');
  }

  if (!ozDeployed) {
    console.log('Deploying OZ account...');

    // DEPLOY_ACCOUNT v3 tx hash
    // OZ account constructor_calldata = [public_key] as a single felt array
    const constructorCalldata = CallData.compile([OZ_PUBKEY]);

    const deployAccountTxHash = hash.calculateDeployAccountTransactionHash({
      contractAddress: OZ_ADDRESS,
      classHash: OZ_CLASS_HASH,
      compiledConstructorCalldata: constructorCalldata,
      salt: OZ_SALT,
      version: '0x3',
      chainId: CHAIN_ID,
      nonce: '0x0',
      resourceBounds: {
        l1_gas: RESOURCE_BOUNDS.l1_gas,
        l2_gas: RESOURCE_BOUNDS.l2_gas,
        l1_data_gas: RESOURCE_BOUNDS.l1_data_gas,
      },
      tip: '0x0',
      paymasterData: [],
      nonceDataAvailabilityMode: 0,
      feeDataAvailabilityMode: 0,
    });

    const sig = signHash(deployAccountTxHash, OZ_PRIVKEY);

    const body = await callRpcRaw('starknet_addDeployAccountTransaction', {
      deploy_account_transaction: {
        type: 'DEPLOY_ACCOUNT',
        version: '0x100000000000000000000000000000003',
        class_hash: OZ_CLASS_HASH,
        contract_address_salt: OZ_SALT,
        constructor_calldata: constructorCalldata,
        signature: sig,
        nonce: '0x0',
        resource_bounds: {
          l1_gas: RESOURCE_BOUNDS.l1_gas,
          l2_gas: RESOURCE_BOUNDS.l2_gas,
          l1_data_gas: RESOURCE_BOUNDS.l1_data_gas,
        },
        tip: '0x0',
        paymaster_data: [],
        nonce_data_availability_mode: 'L1',
        fee_data_availability_mode: 'L1',
      },
    });

    console.log('Deploy account raw response:', JSON.stringify(body, null, 2));
    if (body.error) throw new Error(`Deploy account failed: ${JSON.stringify(body.error)}`);

    console.log('Deploy account tx:', body.result.transaction_hash);
    console.log('Waiting...');
    await provider.waitForTransaction(body.result.transaction_hash);
    console.log('OZ account deployed!');
  }

  // ── Step 2: Declare CommitmentRegistry ────────────────────────────────────
  const sierraContract = json.parse(readFileSync(SIERRA_FILE).toString());
  const classHash = hash.computeContractClassHash(sierraContract);
  console.log('\nSierra class hash:', classHash);

  const sierraForRpc = {
    sierra_program: sierraContract.sierra_program,
    contract_class_version: sierraContract.contract_class_version,
    entry_points_by_type: sierraContract.entry_points_by_type,
    abi: typeof sierraContract.abi === 'string'
      ? sierraContract.abi
      : JSON.stringify(sierraContract.abi),
  };

  let alreadyDeclared = false;
  try {
    await provider.getClassByHash(classHash);
    console.log('Already declared on-chain.');
    alreadyDeclared = true;
  } catch { /* not yet */ }

  if (!alreadyDeclared) {
    const nonce = toHex(await provider.getNonceForAddress(OZ_ADDRESS));
    console.log('OZ nonce:', nonce);

    const declareTxHash = hash.calculateDeclareTransactionHash({
      senderAddress: OZ_ADDRESS,
      classHash,
      compiledClassHash: NETWORK_CASM_HASH,
      version: '0x3',
      nonce,
      chainId: CHAIN_ID,
      resourceBounds: {
        l1_gas: RESOURCE_BOUNDS.l1_gas,
        l2_gas: RESOURCE_BOUNDS.l2_gas,
        l1_data_gas: RESOURCE_BOUNDS.l1_data_gas,
      },
      tip: '0x0',
      paymasterData: [],
      accountDeploymentData: [],
      nonceDataAvailabilityMode: 0,
      feeDataAvailabilityMode: 0,
    });

    const sig = signHash(declareTxHash, OZ_PRIVKEY);

    const body = await callRpcRaw('starknet_addDeclareTransaction', {
      declare_transaction: {
        type: 'DECLARE',
        version: '0x100000000000000000000000000000003',
        sender_address: OZ_ADDRESS,
        compiled_class_hash: NETWORK_CASM_HASH,
        contract_class: sierraForRpc,
        signature: sig,
        nonce,
        resource_bounds: {
          l1_gas: RESOURCE_BOUNDS.l1_gas,
          l2_gas: RESOURCE_BOUNDS.l2_gas,
          l1_data_gas: RESOURCE_BOUNDS.l1_data_gas,
        },
        tip: '0x0',
        paymaster_data: [],
        nonce_data_availability_mode: 'L1',
        fee_data_availability_mode: 'L1',
        account_deployment_data: [],
      },
    });

    console.log('\nDeclare raw response:', JSON.stringify(body, null, 2));
    if (body.error) throw new Error(`Declare failed: ${JSON.stringify(body.error)}`);

    console.log('Declare tx hash:', body.result.transaction_hash);
    console.log('Waiting for declare...');
    await provider.waitForTransaction(body.result.transaction_hash);
    console.log('Contract declared!');
  }

  // ── Step 3: Deploy contract instance ──────────────────────────────────────
  console.log('\nDeploying contract instance...');
  const account = new Account(provider, OZ_ADDRESS, OZ_PRIVKEY, undefined, '0x3');
  const deployResponse = await account.deployContract({
    classHash,
    constructorCalldata: CallData.compile({}),
  });

  console.log('Deploy tx:', deployResponse.transaction_hash);
  await provider.waitForTransaction(deployResponse.transaction_hash);

  const contractAddress = deployResponse.contract_address;
  console.log('\n✓ Deployed!');
  console.log('Contract address:', contractAddress);

  if (existsSync(RELAY_ENV)) {
    let env = readFileSync(RELAY_ENV, 'utf8');
    env = env.replace(/COMMITMENT_REGISTRY_ADDRESS=.*/, `COMMITMENT_REGISTRY_ADDRESS=${contractAddress}`);
    writeFileSync(RELAY_ENV, env);
    console.log('Updated packages/relay/.env');
  }

  console.log('\nVoyager: https://sepolia.voyager.online/contract/' + contractAddress);
}

main().catch(err => {
  console.error('\nFailed:', err.message ?? err);
  process.exit(1);
});
